Repository GSG-G11/tender-shoots, pull requests merged in 2022-04, with the labels that each got.

#8 create generic button
  package-lock.json
  package.json
  src/App.js
  src/componenets/UI/Button/Button.css
  src/componenets/UI/Button/Button.js
  src/componenets/UI/index.js
Labels: approved

#9 create Color Actions Component
  src/componenets/Actions/Actions.css
  src/componenets/Actions/Actions.js
Labels: Awaiting Review

#10 create navbar and fix a typo in the component folder
  public/index.html
  src/App.css
  src/App.js
  src/components/Actions/Actions.css
  src/components/Actions/Actions.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/UI/Button/Button.css
  src/components/UI/Button/Button.js
  src/components/UI/index.js
Labels: Awaiting Review

#12 create loader component
  src/components/UI/Loader/Loader.css
  src/components/UI/Loader/Loader.js
  src/components/UI/index.js
Labels: approved

#14 create home component
  package-lock.json
  src/Pages/Home/Home.js
  src/components/Actions/Actions.css
  src/components/Actions/Actions.js
  src/components/ColorBoard/ColorBoard.css
  src/components/ColorBoard/ColorBoard.js
  src/components/UI/Button/Button.css
Labels: Awaiting Review

#15 create favorits route
  .vscode/settings.json
  src/App.js
  src/Pages/favorites /Favorites.css
  src/Pages/favorites /Favorites.js
  src/components/Actions/Actions.js
Labels: approved

#19 update favorite routes
  package-lock.json
  src/App.js
  src/Pages/Home/Home.js
  src/Pages/favorites/Favorites.css
  src/Pages/favorites/Favorites.js
  src/Pages/index.js
  src/components/Actions/Actions.js
  src/components/ColorBoard/ColorBoard.css
  src/components/UI/Button/Button.js
  src/components/UI/Loader/Loader.css
  src/components/UI/Loader/Loader.js
Labels: Awaiting Review

#21 create paint app with som fix
  .vscode/settings.json
  public/index.html
  src/App.js
  src/Pages/Paint/Paint.css
  src/Pages/Paint/Paint.js
  src/Pages/index.js
  src/components/Navbar/Navbar.js
  src/components/PaintMenu/PaintMenu.js
  src/components/UI/Input/input.js
  src/components/UI/index.js
Labels: approved

#22 Write README
  README.md
Labels: Done
